ECHO OFF
SETLOCAL EnableDelayedExpansion
REM ----------------------------------------------------------------
REM launch the MDI web server and browser client in 'public' mode
REM     web server  runs on a remote AWS EC2 instance in the cloud
REM     web browser runs on a user's local desktop/laptop computer
REM     thus, address entered into web browser is "https://example.org"
REM -----------------------------------------------------------------------
REM this script was generated by XXXX.shinyapps.io
REM GitHub repository for script generator: https://github.com/MiDataInt/mdi-script-generator
REM script template author: Thomas E. Wilson, https://wilsonte-umich.github.io/
REM ----------------------------------------------------------------

REM -----------------------------------------------------------------------
REM set variable values
REM -----------------------------------------------------------------------
SET SERVER_URL=__SERVER_URL__

REM -----------------------------------------------------------------------
REM prompt the user for the requested action
REM -----------------------------------------------------------------------
ECHO.
ECHO Welcome to the Michigan Data Interface.
ECHO.
ECHO What would you like to do to public server %SERVER_URL%?
ECHO.
ECHO   Server execution commands (in order of usage):
ECHO     build     run docker-compose build to create all needed Docker images
ECHO     install   update the server config, clone GitHub repos, install R packages
ECHO     up        launch all containers to run the MDI apps server
ECHO     down      stop and remove any running containers to shut down the apps server
ECHO.
ECHO   Additional resource management commands:
ECHO     edit      use nano to edit one of the server configuration files
ECHO     bash      bring up an interactive bash terminal in a new apps-server container
ECHO.
SET /p ACTION_NAME=Please type a command name (Enter to do nothing): 

REM exit and do nothing
IF "%ACTION_NAME%"=="" (
    ENDLOCAL
    EXIT

REM request the file to edit
) ELSE IF "%ACTION_NAME%"=="edit" (

REM send all other actions directly to server via SSH
) ELSE (
    ssh ubuntu@%SERVER_URL% /srv/mdi/server %ACTION_NAME%
)

ENDLOCAL

PAUSE
